// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpZegeJC2X6xrsqYC7OH9q120oujC8_gk',
    appId: '1:122572465005:web:47f911e5147ab89326f064',
    messagingSenderId: '122572465005',
    projectId: 'the-vet-app-flutter',
    authDomain: 'the-vet-app-flutter.firebaseapp.com',
    storageBucket: 'the-vet-app-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBadT3R328CnI5r2QGUkDj2tyvWW9tgg_c',
    appId: '1:122572465005:android:b052fbece08d0bd126f064',
    messagingSenderId: '122572465005',
    projectId: 'the-vet-app-flutter',
    storageBucket: 'the-vet-app-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcH6FhvtRGOPpYC4sgHdYImjbMH92G9tY',
    appId: '1:122572465005:ios:8f040cba6d3d15e726f064',
    messagingSenderId: '122572465005',
    projectId: 'the-vet-app-flutter',
    storageBucket: 'the-vet-app-flutter.appspot.com',
    iosBundleId: 'com.example.theVetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcH6FhvtRGOPpYC4sgHdYImjbMH92G9tY',
    appId: '1:122572465005:ios:0b5b0d21fd500ff426f064',
    messagingSenderId: '122572465005',
    projectId: 'the-vet-app-flutter',
    storageBucket: 'the-vet-app-flutter.appspot.com',
    iosBundleId: 'com.example.theVetApp.RunnerTests',
  );
}
